### ISSUE TITLE
Impossible to use Boom library for Hapi

### ISSUE THREAD

**Issue by rusfearuth** [apollographql/graphql-server#175]
I tried to generate http error by means [Boom](https://github.com/hapijs/boom). It should call into apolloOptions as a function. Unfortunately, Boom error was catch by **getApolloOptions** and converted to error with status code 500.

Could you add support for using custom errors?

**Comment by rusfearuth** [comment]
Here is example how to fix it.

https://github.com/rusfearuth/apollo-server/commit/9c721cd440b163f955280d527dea43e270b3a3f7

**Comment by DxCx** [comment]
initially i tought that this is very poor solution as this will handle very specific cases.
but then i realized boom is part of hapi error handling, so it's looks good IMO,
would you mind rebase it upon the mono repo and open a PR?

**Comment by DxCx** [comment]
well looks like @rusfearuth is not responding..
anyone else is interested in this?

**Comment by PizzaBrandon** [comment]
I'm needing the same thing. I'll take this up.

**Comment by PizzaBrandon** [comment]
Well, I spoke too early...

Based on how the mono repo was refactored, the options function still can't throw a `Boom` because it will get caught up in `runHttpQuery`. (https://github.com/apollostack/graphql-server/blob/master/packages/graphql-server-core/src/runHttpQuery.ts#L36)

It would require some duplication of code to pre-execute the options function in the `runHttpQueryWrapper` in the hapi package (https://github.com/apollostack/graphql-server/blob/master/packages/graphql-server-hapi/src/hapiApollo.ts#L22) and then sending the finalized options object to `runHttpQuery` (or throwing the Boom).

I was thinking we could have handled a `Boom` response from the actual execution of a request against the compiled schema, but the `execute` function from the `graphql` package only resolves and outputs an ExecutionResult, which is just `{ data: {}, errors: [] }`.

If we want to go the code duplication route, I think I have the code completed for that, otherwise I suspect this request should be closed.

**Comment by DxCx** [comment]
hi @PizzaBrandon since im not that familiar with Boom,
can you please submit a failing test so i can dig deeper?

**Comment by PizzaBrandon** [comment]
I was coding by inspection before and don't have a failing test at this time. I'll see if I can pull something together by the end of this week, otherwise I think this issue can probably be closed based on the above analysis.

**Comment by DxCx** [comment]
alright cool thanks @PizzaBrandon  :)

**Comment by Samueljoli** [comment]
@PizzaBrandon @DxCx Hey just snooping around, any update on this?

**Comment by helfer** [comment]
Closing this based on comment from @PizzaBrandon on Jan 27.
