### ISSUE TITLE
`graphqlExpress` swallows an error thrown in a resolver

### ISSUE THREAD

**Issue by edoroshenko** [apollographql/graphql-server#313]
In express application when my resolver throws an error, `graphql-server-express` hangs. It doesn't respond and doesn't throw an error.

I've dug a little and it looks like I've found the reason. The error thrown here: https://github.com/apollographql/graphql-server/blob/master/packages/graphql-server-express/src/expressApollo.ts#L40 will not be caught and will not be passed through, because `express` expects using `next` callback with error object passed.

> If you pass anything to the next() function (except the string 'route'), Express regards the current request as being in error and will skip any remaining non-error handling routing and middleware functions.

(from here: http://expressjs.com/en/guide/error-handling.html)

So actually I could easily create a pull-request, but when I started taking a look at the tests, I found out that there's a central test, that covers all the frameworks. So it should be fixed for all the server frameworks, so the scope is quite wide.

So I would propose to define the proper behaviour first. Actually there are two options:
1. To pass an error through to be caught outside of graphql middleware
2. To respond with 500, because schema doesn't seem to be valid (as resolver doesn't work properly)

I would prefer the first option, because then it'll be easier to log it depending on developer's preference.

**Comment by theboolean** [comment]
Another approach could be to return `runHttpQuery` instead of nothing, to handle the rejection of the promise

**Comment by edoroshenko** [comment]
@theboolean did you mean "return `HttpQueryError`"?
If yes, that is what I mean by writing "pass through".

**Comment by theboolean** [comment]
@edoroshenko nope, I meant to return `runHttpQuery` at [line 30](https://github.com/apollographql/graphql-server/blob/master/packages/graphql-server-express/src/expressApollo.ts#L30). In this way we can handle the rejection of the promise at a higher level.

**Comment by DxCx** [comment]
hmm..
if resolver failed, then `express` shouldn't respond with an error, transport did it work correctly.
you should get `200` status with `{ errors: [....] }`
at the moment you don't get ANY thing?
can you eleborate which error is that?

**Comment by kylecordes** [comment]
Does this issue leave `graphql-server-express` essentially unusable until fixed?

**Comment by DxCx** [comment]
why unusable?
i still didn't see any in-depth info of the issue,
all i know is that i am using `graphql-sever-express` and it is working as expected...

**Comment by DxCx** [comment]
Alright, so since i'm using `graphql-server-express` myself, and for me it works (maybe you are using older express version? or we are using it in a different way maybe?) i didn't notice that..
anyway, yes, according to express documentation you are correct, error should pass through next,
would you like to open a quick PR for fixing that?

**Comment by helfer** [comment]
@edoroshenko could you provide a reproduction for this? There are hundreds of people using graphql-server-express without issues, and I would bet many of them throw errors inside resolvers. While express wants errors to be passed into the `next()` call, the GraphQL spec clearly specifies that errors thrown inside resolvers should be put into the `errors: []` part of the GraphQL response. It says nothing about the HTTP status code that should be returned.
As far as I can tell, the only (minor) issue here is that these errors aren't passed to the next middleware in express, which should be really easy to fix. I don't think this is a blocker for 99% of people, because I've seen very few graphql servers that have additional middleware after the GraphQL part.

**Comment by DxCx** [comment]
well @helfer, his explanation is abit tricky, you are totally correct and that's what i said before without getting too much into it that errors from resolvers should be under errors as transport layer "success".
however, in this case, the code marked is not related to errors in resolvers, but for errors in graphql-server-core layer, which should be passed in `next` and not thrown.

**Comment by helfer** [comment]
@DxCx ah, I see, that makes more sense. Let's fix that.

**Comment by babsonmatt** [comment]
I believe the same issue exists with the koa package as well

**Comment by edoroshenko** [comment]
@helfer do you still need a reproduction? (sorry for late response)

**Comment by helfer** [comment]
@edoroshenko I don't think we need a reproduction. If you could make a PR with a test and a fix, that would be great! 🙏
